- name: Setup New Relic
  hosts: all
  gather_facts: False
  tasks:
  - name: wait until able to reachable
    wait_for_connection:
      delay: 60
      timeout: 300
  roles:
  - { role: li-newrelic, when: ansible_os_family == "RedHat" }
  - { role: win-newrelic, when: ansible_os_family == "Windows" }
