- name: Setup New Relic on Linux
  hosts: linux
  roles:
  - role: li-newrelic

- name: Setup New Relic on Windows
  hosts: windows
  roles:
  - role: win-newrelic

# - name: New Relic setup
#   hosts: all
#   roles:
#   - { role: li-nr, when: ansible_os_family == "RedHat" }
#   - { role: win-nr, when: ansible_os_family == "Windows" }