  - name: wait until able to reachable
    wait_for_connection:
      delay: 30
      timeout: 300
  - name: Ping check hosts
    ansible.builtin.ping:
  - name: Print message
    ansible.builtin.debug:
      msg: Able to connect host
  - name: add license key
    copy:
      dest: "/etc/newrelic-infra.yml"
      content: |
        license_key: {{ newrelic_license_key }}
    become: true
    become_user: root
  - name: Download New Relic agent
    ansible.builtin.shell:
      cmd: "sudo curl -o /etc/yum.repos.d/newrelic-infra.repo {{ newrelic_linux_url }}"
      chdir: /etc/yum.repos.d
    become: true
    become_user: root
  - name: Install New Relic agent
    ansible.builtin.yum:
      name: newrelic-infra
      enablerepo: newrelic-infra
      state: present
    become: true
    become_user: root
  - name: Start New Relic agent
    command: systemctl restart newrelic-infra
    become: true
    become_user: root