- name: New Relic setup
  hosts: linux
  gather_facts: no
  tasks:
    - name: wait until able to reachable
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Gather facts for first time
      setup:
    - name: Ping check hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Able to connect host
    - name: add license key
      copy:
        dest: "/etc/newrelic-infra.yml"
        content: |
          license_key: e8633494910348db21863d93101da438ffc0NRAL
      become: true
      become_user: root
    - name: Download New Relic agent
      ansible.builtin.shell:
        cmd: "sudo curl -o /etc/yum.repos.d/newrelic-infra1.repo https://download.newrelic.com/infrastructure_agent/linux/yum/amazonlinux/2/x86_64/newrelic-infra.repo "
        chdir: /etc/yum.repos.d
      become: true
      become_user: root