- name: New Relic setup
  hosts: windows
  gather_facts: no
  tasks:
    - name: wait until able to reachable
      wait_for_connection:
        delay: 60
        timeout: 300
    - name: Gather facts for first time
      setup:
    - name: Ping check hosts
      ansible.windows.win_ping:
    - name: Check logged user
      ansible.windows.win_whoami: