  - name: wait until able to reachable
    wait_for_connection:
      delay: 60
      timeout: 300
  - name: Ping check hosts
    ansible.windows.win_ping:
  - name: Check logged user
    ansible.windows.win_whoami:
  - name: grant the ansible user the SeTcbPrivilege right
    ansible.windows.win_user_right:
      name: SeTcbPrivilege
      users: '{{ansible_user}}'
      action: add
  - name: Download New Relic installer
    win_get_url:
      url: '{{ newrelic_windows_url }}'
      dest: C:\Users\localadmin\newrelic-infra.msi
  - name: Install New Relic agent
    win_package:
      path: C:\Users\localadmin\newrelic-infra.msi
      state: present
  - name: Add license key
    community.windows.win_lineinfile:
      path: C:\Program Files\New Relic\newrelic-infra\newrelic-infra.yml
      regex: '^license_key:'
      line: 'license_key: {{ newrelic_license_key }}'
  - name: Restart a service
    ansible.windows.win_service:
      name: newrelic-infra
      state: restarted